name: Format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: JKRT/julia-format@master
      with:
        args: -i 2 -v .
