name: Format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: julia-actions/@JKRT/julia-format.git
      with:
        args: -i 2 -v .
